export const FETCH_GRAPH_DATA = 'FETCH_GRAPH_DATA';
export const SAVE_GRAPH_PARAMS = 'SAVE_GRAPH_PARAMS';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';
